### ISSUE TITLE
Python 2.6: undefined symbol: Py_TOUPPER

### ISSUE THREAD

**Issue by jayvdb** [mikekap/unicodedata2#2]
unicodedata2 compiles OK on Python2.6.6, but on import it fails.

```
$ python2.6
Python 2.6.6 (r266:84292, Jun 18 2015, 19:35:20) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-7)] on linux4
Type "help", "copyright", "credits" or "license" for more information.
>>> import unicodedata2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/python2.6/site-packages/unicodedata2.so: undefined symbol: Py_TOUPPER
```

On Python 2.7 it works OK.

**Comment by jayvdb** [comment]
After more testing, it appears that Py_TOUPPER was introduced in v2.7.3.

The change to unicodedata was https://hg.python.org/cpython/rev/60d80880bf88

I assume that it was part of http://bugs.python.org/issue1813

**Comment by jayvdb** [comment]
Python v2.7.0-2 did not expose _Py_ctype_toupper using __declspec(dllexport), so on Windows the linking fails with:

```
unicodedata.obj : error LNK2019: unresolved external symbol _Py_ctype_toupper referenced in function _gethash
build\lib.win-amd64-2.7\unicodedata2.pyd : fatal error LNK1120: 1 unresolved externals
```

**Comment by jayvdb** [comment]
Thanks for merging.  Could a new release be uploaded to pypi so that I can use that as a dependency instead of a git+... dependency?

**Comment by mikekap** [comment]
Released - 7.0.0-2 is live.
